version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: puppeteer
    versions:
    - ">= 0"
  - dependency-name: js-yaml
    versions:
    - 4.0.0
